### ISSUE TITLE
3D display of whole Molecules

### ISSUE THREAD

**Issue by vincefn** [vincefn/objcryst#20]
From JG:
In the past FOX program, the unit cell plane did not randomly cut off molecules, why does the new FOX program cut molecules?

In the past version of Fox, even if the display limit is adjusted, the geometry that is packed inside the unit cell is clearly visible because it disappears or appears in molecular units.

**Comment by vincefn** [comment]
The reason for the change in the display mode was the following:
- in the past versions (1.9.7), the display policy for molecules was 'if the center of the molecule is in the display range, then display the whole molecule'
- one consequence is that for molecules extending beyond a single unit cell, atoms which were inside the display range could be not displayed, if the center of the molecule was beyond the display range. 
- This made looking at single molecule conformation easy, but looking at distances with neighbouring atoms/molecules could be completely incorrect

For those reasons I won't go back to the previous behaviour. The latest version gives shortcuts allowing to easily tweak the display limits to explore the unit cell.
However what can be added (but it's a bit complicated in the current code) is, in addition to always displaying all atoms inside the display range, to force displaying the complete Molecule when its center is inside the display range

**Comment by MatthewKAIST** [comment]
I would like to be happy, if the latter display option that you mentioned could be imbedded in the new FOX.

**Comment by vincefn** [comment]
I forgot to mention when closing this, that you can now use a number of shortcuts to toggle the 3d display behaviour. Use 'h' to get the help in the 3d window
