### ISSUE TITLE
Bug Hunting: Free Objects for Crystallography "FOX-2017-06-28.exe stopped working" error during Debug Test !

### ISSUE THREAD

**Issue by emirfirlar** [vincefn/objcryst#32]
https://i.hizliresim.com/Z9kLb0.jpg
&emsp;
#### <h1>Expected behavior</h1>
&emsp;
<h3>Doing “Debug Test” </h3>
&emsp;
#### <h1>Actual behavior</h1>
&emsp;
<h3>FOX-2017-06-28.exe stopped working </h3>
&emsp;
#### <h1>How to reproduce</h1>
&emsp;

I opened K-tartrate.xml file. I did “convert atoms to a molecule” in scatterers section. I chose K atom in “choose the molecule’s atoms” window. I clicked Formula & Restraints button in Molecule section. Then, i chose Debug Test. The program stopped working. I checked the error again. This time i created new crystal in objects menu. I chose “add atomic scattering power” in scatterers section. Afterwards, i clicked to add atom. “Choose an atom type (scattering power)” window has opened. I chose scattering power atom in this window. Then i did “convert atoms to a molecule” in scatterers section. I clicked on Formula & Restraints button in the opening section. I chose Debug Test in this section. The program stopped working again. When i did the debug test, the program gives error. This error should be fixed. 

* Browser: Google Chrome
63.0.3239.132 (Official) 

* Operating system: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM

* Program Version: F.O.X Free Objects for Crystallography 2017.2  

&emsp;
#### <h1>Recording Of The Bug</h1>
&emsp;
* Formula & Restraints –Debug Test Gif’s: 
&emsp;

<center> https://i.hizliresim.com/m26rV4.gif </center>

&emsp;

* You can see the error in the first video in detail below: 

&emsp;

<iframe width="854" height="480" src="https://www.youtube.com/embed/1QeNF_DXstc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

* You can see the error again in the second video in detail below: 

&emsp;

<iframe width="854" height="480" src="https://www.youtube.com/embed/I6inOR-iCSs" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

<h3><center>“The Debug Test” feature are ending up with shutdown of the program in the situations above</center> 
&emsp;
<center>The FOX program is not responding.</center> 
&emsp;
<center>This error should be fixed !</center></h3>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-hunting-free-objects-for-crystallography-fox-2017-06-28-exe-stopped-working-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by vincefn** [comment]
This was due to the special case of a single-atom molecule. Maybe would also occur if a molecule atom was not linked to any other.
Fixed in 3ec8cf553fb6b242ab4e9af1cfa7556e1f29d092 and also 47b7e19d925701cee47fc38011b1a0ef4ec44c8d (similar issue).
