### ISSUE TITLE
Compilation issues on Arch Linux

### ISSUE THREAD

**Issue by ChlorisPaleGreen** [vincefn/objcryst#40]
# The Issue
Compilation of Fox (2017.2 or git cloned) on Arch Linux fails due to two (or three if using shared libs) compiler errors. I am using gcc version 8.1.0.

# Error Messages
**The first one is about using deleted function in boost::shared_ptr.**
`wxCrystal.cpp: In member function ‘void ObjCryst::WXGLCrystalCanvas::OnUpdateUI(wxUpdateUIEvent&)’:
wxCrystal.cpp:3996:126: error: use of deleted function ‘boost::shared_ptr<ObjCryst::UnitCellMap>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMap>&)’
          boost::shared_ptr<ObjCryst::UnitCellMap> pMap=mvpUnitCellMap[mpFourierMapListWin->mpAvailableMapList->GetSelection()];
                                                                                                                              ^
In file included from /home/chloris/tmp/Fox/ObjCryst/wxCryst/../../static-libs/include/boost/shared_ptr.hpp:17,
                 from /home/chloris/tmp/Fox/ObjCryst/wxCryst/../../ObjCryst/../ObjCryst/wxCryst/wxCrystal.h:30,
                 from wxCrystal.cpp:35:
/home/chloris/tmp/Fox/ObjCryst/wxCryst/../../static-libs/include/boost/smart_ptr/shared_ptr.hpp:158:25: note: ‘boost::shared_ptr<ObjCryst::UnitCellMap>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMap>&)’ is implicitly declared as deleted because ‘boost::shared_ptr<ObjCryst::UnitCellMap>’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^~~~~~~~~~
wxCrystal.cpp: In member function ‘void ObjCryst::WXGLCrystalCanvas::OnFourier(wxCommandEvent&)’:
wxCrystal.cpp:4279:126: error: use of deleted function ‘boost::shared_ptr<ObjCryst::UnitCellMap>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMap>&)’
          boost::shared_ptr<ObjCryst::UnitCellMap> pMap=mvpUnitCellMap[mpFourierMapListWin->mpAvailableMapList->GetSelection()];
                                                                                                                              ^
wxCrystal.cpp:4290:128: error: use of deleted function ‘boost::shared_ptr<ObjCryst::UnitCellMapGLList>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMapGLList>&)’
          boost::shared_ptr<UnitCellMapGLList> pMap=mvpUnitCellMapGLList[mpFourierMapListWin->mpDisplayedMapList->GetSelection()];
                                                                                                                                ^
In file included from /home/chloris/tmp/Fox/ObjCryst/wxCryst/../../static-libs/include/boost/shared_ptr.hpp:17,
                 from /home/chloris/tmp/Fox/ObjCryst/wxCryst/../../ObjCryst/../ObjCryst/wxCryst/wxCrystal.h:30,
                 from wxCrystal.cpp:35:
/home/chloris/tmp/Fox/ObjCryst/wxCryst/../../static-libs/include/boost/smart_ptr/shared_ptr.hpp:158:25: note: ‘boost::shared_ptr<ObjCryst::UnitCellMapGLList>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMapGLList>&)’ is implicitly declared as deleted because ‘boost::shared_ptr<ObjCryst::UnitCellMapGLList>’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^~~~~~~~~~
wxCrystal.cpp:4302:126: error: use of deleted function ‘boost::shared_ptr<ObjCryst::UnitCellMap>::shared_ptr(const boost::shared_ptr<ObjCryst::UnitCellMap>&)’
          boost::shared_ptr<ObjCryst::UnitCellMap> pMap=mvpUnitCellMap[mpFourierMapListWin->mpAvailableMapList->GetSelection()];
                                                                                                                              ^
make[2]: *** [gnu.mak:26: wxCrystal.o] Error 1
make[2]: Leaving directory '/home/chloris/tmp/Fox/ObjCryst/wxCryst'
make[1]: *** [/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/rules.mak:299: libwxCryst] Error 2
make[1]: Leaving directory '/home/chloris/tmp/Fox/Fox/src'
make: *** [Makefile:16: Fox] Error 2`

Possible solution (that works) is proposed [here](https://stackoverflow.com/questions/18900730/boostshared-ptrshared-ptrconst-boostshared-ptr-is-implicitly-declared#18900875). I fixed it by adding `shared_ptr(const shared_ptr&) = default;` in file `static-libs/include/boost/smart_ptr/shared_ptr.hpp` under `public:` in class `template<class T> class shared_ptr`. Though upgrading the bundled Boost might be a better option.

**The second one is about convertion of `false` to `void*`.**
`FoxServerThread.cpp: In member function ‘virtual void* FoxServerThread::Entry():
FoxServerThread.cpp:73:18: error: cannot convert ‘bool’ to ‘void*’ in return
           return false;
                  ^~~~~
make[2]: *** [gnu.mak:25: FoxServerThread.o] Error 1
make[2]: Leaving directory '/home/chloris/tmp/Fox/Fox/src'
make[1]: *** [gnu.mak:37: Fox] Error 2
make[1]: Leaving directory '/home/chloris/tmp/Fox/Fox/src'
make: *** [Makefile:16: Fox] Error 2`

I solved it by replacing `return false;` with `return (void*)false;` in line number 73 of file `Fox/src/FoxServerThread.cpp`. Though this is a dirty trick and it would probably be best not to use void* altogether.

**The third one I only encountered when using shared wxgtk, freeglut and fftw, is about missing library.**
`g++  -L/usr/lib -L/usr/local/lib -L/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/CrystVector -L/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/ObjCryst -L/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/RefinableObj -L/home/chloris/tmp/Fox/Fox/src/../../static-libs/lib -L/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/Quirks -L/home/chloris/tmp/Fox/Fox/src/../../ObjCryst/wxCryst -L/x86_64/lib -o Fox  Fox.o FoxJob.o GridResult.o IOSocket.o FoxServerThread.o FoxServer.o FoxClient.o WXFoxClient.o WXFoxServer.o WXGridWindow.o -lm -lcryst -lCrystVector -lQuirks -lRefinableObj -lcctbx /home/chloris/tmp/Fox/Fox/src/../../static-libs/lib/libnewmat.a   -L/usr/X11R6/lib -lwxcryst wx-config --unicode=yes --libs adv,core,base,net wx-config --unicode=yes --gl-libs -lGL -lGLU -lglut -lfftw3f /home/chloris/tmp/Fox/Fox/src/../../static-libs/lib/libmysqlclient.a
/usr/bin/ld: /home/chloris/tmp/Fox/Fox/src/../../static-libs/lib/libmysqlclient.a(client_plugin.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [gnu.mak:38: Fox] Error 1
make[1]: Leaving directory '/home/chloris/tmp/Fox/Fox/src'
make: *** [Makefile:16: Fox] Error 2`

I solved it by adding `-ldl` in front of `...static-libs/lib/libmysqlclient.a` of the last g++ command.
# How to Reproduce
Follow instructions [here](http://fox.vincefn.net/Compile/Linux) (Get Latest Fox from git repository (RECOMMENDED)). I used `make` (with Fox 2017.2) to produce the first two issues and `make shared-wxgtk=1 shared-glut=1 shared-fftw=1` (with git-cloned Fox) to produce all three of them.
# Additional Notes
When running Fox compiled using shared libraries, I got message
`09:38:30: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1012,wx containers,compatible with 2.8).`

I did not get such messages when I compiled Fox with static libraries.

**Comment by ChlorisPaleGreen** [comment]
I've encountered the same compilation issues on Fedora 28 workstation edition using gcc 8.1.1 so there is no need to use Arch Linux, which is time consuming to set up, to reproduce them.

**Comment by vincefn** [comment]
Oups it seems I never saw a notification about this issue, which I just discover as someone else had a similar issue (as 1 and 2). 

The first issue was due to boost version which was too old. The cctbx archive auto-downloaded from sourceforge has been updated.

The second issue was fixed yesterday (in git version).

The last issue, I don't know.. probably a conflict between versions of an installed mysql and the static one ? And same for wx I guess. Maybe leftover headers from static libraries installation.

**Comment by srtlg** [comment]
@ChlorisPaleGreen I've submitted a package to [AUR](https://aur.archlinux.org/packages/objcryst-fox/)

The warning you encounter has to do with wxgtk on Arch. It is usually harmless, at least I didn't encounter problems by using kicad-git (which also uses wxgtk). I think you can get rid of it by re-compiling wxgtk.

**Comment by ChlorisPaleGreen** [comment]
@vincefn I've tried to recompile the latest Git version of Fox and I can confirm that the first two issues are fixed indeed. Nice work, thanks. Though I still need to manually add `-ldl` to the final compilation command that produces the executable.

@srtlg Thanks for the package. It's always nice to have things controlled by the package manager. There are some things to note. @vincefn has updated the cctbx archive and checksum needs to be updated. And you should add `rsync` to the list of make dependencies. I didn't have it installed and got a make error. `makepkg` also issued a warning that package files contain a reference to srcdir, but I checked and did not find any such reference. To sum it up, after I updated the checksum and installed rsync the package compiled flawlessly.

Finally, I get no mismatch warnings at startup from either of the builds.

**Comment by srtlg** [comment]
@ChlorisPaleGreen I uploaded your proposed changes to AUR.

**Comment by ChlorisPaleGreen** [comment]
@srtlg Thank you. I've tested the latest AUR package and it builds gracefully.

Since all the matters are resolved, I am closing this issue. The remaining thing that might be worth taking a look at is the need to append `-ldl` to final linking command. There was no need to do that when building the AUR package so there must be a solution.

**Comment by srtlg** [comment]
@ChlorisPaleGreen Sorry, I didn't realize immediately what you meant by `-ldl`.  Apparently you are not using the shared library version of `libmysqlclient` (because it is in `static-libs`).  The AUR package uses the shared version (albeit now reference remains in the built executable).
