### ISSUE TITLE
location of boost_1_68_0

### ISSUE THREAD

**Issue by srtlg** [vincefn/objcryst#54]
in `ObjCryst/rules-gnu.mak` there is the line

```
$(BUILD_DIR)/boost_1_68_0.tar.bz2:
	cd $(BUILD_DIR) && $(DOWNLOAD_COMMAND) https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2
```
however that URL is no longer available. Is that particular version of boost required? Currently 
[boost.org](https://www.boost.org/users/history/version_1_68_0.html) points to 
`http://boostorg.jfrog.io/artifactory/main/release/1.68.0/source/boost_1_68_0.tar.bz2`

**Comment by vincefn** [comment]
Can you try replacing the URL with https://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.bz2
That link should be more reliable.
More recent versions are likely to work though.
