### ISSUE TITLE
2022.1 Release?

### ISSUE THREAD

**Issue by swt2c** [vincefn/objcryst#55]
ChangeLog.txt seems to indicate there was a 2022.1 release, but I can't find this release on the Releases page or Tags page.  Was this a real release and if so, could you tag/release it please?  Thanks.

**Comment by vincefn** [comment]
Sorry, it was still tagged as a draft, it should be public now - https://github.com/vincefn/objcryst/releases/tag/v2022.1

**Comment by swt2c** [comment]
Thanks!
