### ISSUE TITLE
The time of flight(TOF) neutron data can't be input correctly. 

### ISSUE THREAD

**Issue by jingyao0806** [vincefn/objcryst#62]
Hello!

I want to use both XRD and neutron data to do the optimization. There is no problem with the XRD data. However, the Time of flight (TOF) value were changed when select the option of Time of flight. And the le bail fitting can't be conducted.(When I do this the app crashes）
 The PbSO4 tutorial suggestted to choose neutron radiation with a wavelength of 1.909. Is that means only monochromatic beam neutron data could be analyzed? 

I hope the TOF data import and related Lebail fitting problems could be sovled. 
Thank you

**Comment by vincefn** [comment]
If you have an issue with TOF data, you'll need to send me an example dataset, and the exact steps you took to reproduce the issue.

**Comment by jingyao0806** [comment]
Thank you for  your reply. 
OK, I will show you the error at each step. Please find attached Zip file that include dataset and screen shot. The correct TOF value (2000-22000) change to 30-360. After adding the crystalline phase, Pseudo-Voigt profile parameters are not displayed. Runtime error occurs when Le Bail fitting was performed. 
[dataset and screen shot.zip](https://github.com/user-attachments/files/17504080/dataset.and.screen.shot.zip)

**Comment by vincefn** [comment]
Seems the issue is the input data format. There are only two ways to import TOF data: either using the "TOF ISIS X Y Sigma" format, or using a CIF file. Your data format is different, so it ends up interpreted as monochromatic data.

**Comment by jingyao0806** [comment]
TOF ISIS X Y Sigma format works. Thank you!
